"use client";
import { useState, useMemo, useCallback } from "react";
import { motion } from "framer-motion";
import { Trophy, ChevronRight, TrendingUp, Award, Star, Target, Download, Briefcase, Clock, Check } from "lucide-react";
import careerData from "@/data/career-milestones.json";
import { useProgress } from "@/lib/hooks/useProgress";

export default function CareerPage() {
  const { stats, progress } = useProgress();
  const [selectedLevel, setSelectedLevel] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const estimatedLevel = useMemo(() => {
    const total = stats.totalLabs + stats.totalCourses;
    if (total <= 2) return 0;
    if (total <= 10) return 1;
    if (total <= 30) return 2;
    if (total <= 60) return 3;
    if (total <= 100) return 4;
    if (total <= 150) return 5;
    if (total <= 200) return 6;
    return 7;
  }, [stats]);

  const nextLevel = careerData.milestones[Math.min(estimatedLevel + 1, careerData.milestones.length - 1)];
  const currentLevel = careerData.milestones[estimatedLevel];

  const progressToNext = useMemo(() => {
    const total = stats.totalLabs + stats.totalCourses;
    const thresholds = [2, 10, 30, 60, 100, 150, 200, 300];
    const current = thresholds[estimatedLevel] || 0;
    const next = thresholds[Math.min(estimatedLevel + 1, thresholds.length - 1)] || 300;
    return Math.min(Math.round(((total - current) / (next - current)) * 100), 100);
  }, [stats, estimatedLevel]);

  const generatePDF = useCallback(() => {
    setGenerating(true);

    const completedSkills = Object.entries(progress.skillLevels)
      .filter(([, v]) => v >= 3)
      .map(([k]) => k);

    const content = `
╔══════════════════════════════════════════════════════════════════╗
║                                                                  ║
║              🛡️  BUG BOUNTY HUNTER PORTFOLIO  🛡️                ║
║                                                                  ║
╚══════════════════════════════════════════════════════════════════╝

📅 Generated: ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
🎯 Platform: Bug Bounty University v2.0

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊  CAREER SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ${currentLevel.icon}  Current Level:     ${currentLevel.level}
  💰 Earnings Range:    ${currentLevel.range}
  🧪 Labs Completed:    ${stats.totalLabs}
  📚 Courses Completed: ${stats.totalCourses}
  🎯 Skills Rated:      ${stats.totalSkills}/25
  ⚡ Total XP:          ${stats.totalXp}
  🔥 Day Streak:        ${stats.streak}
  📅 Active Days:       ${stats.totalActiveDays}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🏆  CAREER PROGRESSION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${careerData.milestones.map((m, i) => {
  const status = i < estimatedLevel ? "✅" : i === estimatedLevel ? "👉" : "⬜";
  return `  ${status} ${m.icon} ${m.level.padEnd(12)} ${m.range.padEnd(15)} ${i === estimatedLevel ? "← YOU ARE HERE" : ""}`;
}).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯  CURRENT LEVEL SKILLS: ${currentLevel.level}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${currentLevel.skills.map(s => `  • ${s}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🛡️  PROFICIENT SKILLS (Level 3+)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${completedSkills.length > 0 ? completedSkills.map(s => `  ★ ${s} [${progress.skillLevels[s]}/5]`).join("\n") : "  No skills rated level 3+ yet. Rate your skills in the Progress Tracker!"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📈  NEXT MILESTONE: ${nextLevel.level}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Target Range: ${nextLevel.range}
  
  Required Skills:
${nextLevel.skills.map(s => `    □ ${s}`).join("\n")}

  Tasks to Complete:
${nextLevel.tasks.map(t => `    □ ${t}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡  RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${stats.totalLabs < 10 ? "  → Complete more labs to build practical hacking experience\n" : ""}${stats.totalCourses < 20 ? "  → Work through courses for comprehensive knowledge\n" : ""}${stats.totalSkills < 15 ? "  → Rate more skills in the Progress Tracker\n" : ""}${stats.streak < 7 ? "  → Build a longer daily streak for consistency\n" : ""}  → Focus on high-severity vulnerability types (SQLi, RCE, SSRF)
  → Practice writing clear, reproducible reports
  → Automate your recon pipeline for efficiency

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Generated by Bug Bounty University • bugbounty.university
  Keep hunting. Keep learning. Keep growing. 🚀

`.trim();

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bugbounty_portfolio_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    setTimeout(() => setGenerating(false), 1500);
  }, [stats, progress, estimatedLevel, currentLevel, nextLevel]);

  return (
    <div className="max-w-[1600px] mx-auto px-6 py-8 space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3"><Trophy className="w-7 h-7 text-yellow-400" />Career Tracker</h1>
          <p className="text-gray-500 text-sm mt-1 font-mono">Junior → Senior → Elite • Track your bug bounty career trajectory</p>
        </div>
        <button onClick={generatePDF} disabled={generating} className={`px-4 py-2 text-xs font-mono rounded border transition-all flex items-center gap-2 ${generating ? "bg-cyber-green/20 text-cyber-green border-cyber-green/30" : "bg-cyber-blue/20 text-cyber-blue border-cyber-blue/30 hover:bg-cyber-blue/30"}`}>
          {generating ? <><Check className="w-3.5 h-3.5" />Exported!</> : <><Download className="w-3.5 h-3.5" />Export Portfolio</>}
        </button>
      </div>

      {/* Current Level Hero */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6 border-yellow-500/20" style={{ background: "linear-gradient(135deg, rgba(255,215,0,0.05) 0%, rgba(255,45,149,0.05) 100%)" }}>
        <div className="flex items-center gap-6 flex-wrap">
          <div className="text-6xl animate-float">{currentLevel.icon}</div>
          <div className="flex-1 min-w-[200px]">
            <p className="text-xs font-mono text-gray-500 uppercase">Current Level</p>
            <h2 className="text-3xl font-bold" style={{ color: currentLevel.color }}>{currentLevel.level}</h2>
            <p className="text-sm text-gray-400 mt-1">Earnings target: {currentLevel.range}</p>
            {/* Progress to next */}
            <div className="mt-3">
              <div className="flex justify-between text-xs mb-1">
                <span className="text-gray-500">Progress to {nextLevel.level}</span>
                <span className="text-gray-500 font-mono">{progressToNext}%</span>
              </div>
              <div className="w-full h-2 bg-dark-700 rounded-full overflow-hidden">
                <motion.div className="h-full rounded-full bg-gradient-to-r from-yellow-400 to-orange-500" initial={{ width: 0 }} animate={{ width: `${progressToNext}%` }} transition={{ duration: 1, delay: 0.3 }} />
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 shrink-0">
            <div className="text-center">
              <p className="text-3xl font-bold text-white font-mono">{stats.totalXp}</p>
              <p className="text-[10px] text-gray-500 font-mono uppercase">Total XP</p>
            </div>
            <div className="text-center">
              <p className="text-3xl font-bold text-white font-mono">{stats.totalLabs + stats.totalCourses}</p>
              <p className="text-[10px] text-gray-500 font-mono uppercase">Activities</p>
            </div>
            <div className="text-center">
              <p className="text-3xl font-bold text-white font-mono">{stats.streak}</p>
              <p className="text-[10px] text-gray-500 font-mono uppercase">Streak</p>
            </div>
            <div className="text-center">
              <p className="text-3xl font-bold text-white font-mono">{stats.totalSkills}</p>
              <p className="text-[10px] text-gray-500 font-mono uppercase">Skills</p>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Earnings Timeline */}
      <div className="glass-card p-6">
        <h3 className="text-sm font-mono text-white font-bold flex items-center gap-2 mb-4"><TrendingUp className="w-4 h-4 text-cyber-green" />Earnings Trajectory</h3>
        <div className="flex items-end gap-2 h-40">
          {careerData.earnings_chart.map((point, i) => {
            const maxVal = 100000;
            const height = Math.max((point.target / maxVal) * 100, 3);
            const isActive = i <= estimatedLevel;
            const isCurrent = i === estimatedLevel;
            return (
              <motion.div
                key={i}
                className="flex-1 flex flex-col items-center gap-1"
                initial={{ opacity: 0, scaleY: 0 }}
                animate={{ opacity: 1, scaleY: 1 }}
                transition={{ delay: i * 0.1, duration: 0.5 }}
                style={{ transformOrigin: "bottom" }}
              >
                <span className="text-[8px] font-mono text-gray-600">${point.target >= 1000 ? `${point.target / 1000}K` : point.target}</span>
                <div
                  className={`w-full rounded-t transition-all relative ${isActive ? "bg-gradient-to-t from-cyber-green/60 to-cyber-green" : "bg-dark-700"} ${isCurrent ? "ring-2 ring-yellow-400 ring-offset-2 ring-offset-dark-950" : ""}`}
                  style={{ height: `${height}%` }}
                >
                  {isCurrent && <div className="absolute -top-6 left-1/2 -translate-x-1/2 text-xs">👆</div>}
                </div>
                <span className="text-[7px] font-mono text-gray-600 text-center">{point.label.split(" ").slice(0, 2).join(" ")}</span>
              </motion.div>
            );
          })}
        </div>
        {/* Earnings Milestones */}
        <div className="flex justify-between mt-4 pt-4 border-t border-dark-600/30">
          {[
            { label: "$100", desc: "First Bounty", icon: "🎯", achieved: stats.totalLabs >= 5 },
            { label: "$1K", desc: "Consistent", icon: "📈", achieved: stats.totalLabs >= 15 },
            { label: "$10K", desc: "Expert", icon: "💎", achieved: stats.totalLabs >= 50 },
            { label: "$100K", desc: "Elite", icon: "👑", achieved: stats.totalLabs >= 100 },
          ].map((m) => (
            <div key={m.label} className={`text-center ${m.achieved ? "" : "opacity-40"}`}>
              <div className="text-xl mb-1">{m.icon}</div>
              <p className={`text-sm font-bold font-mono ${m.achieved ? "text-cyber-green" : "text-gray-500"}`}>{m.label}</p>
              <p className="text-[10px] text-gray-500">{m.desc}</p>
              {m.achieved && <Check className="w-3 h-3 text-cyber-green mx-auto mt-1" />}
            </div>
          ))}
        </div>
      </div>

      {/* Career Roadmap */}
      <div className="space-y-3">
        <h2 className="text-lg font-bold text-white flex items-center gap-2"><Award className="w-5 h-5 text-yellow-400" />Career Roadmap</h2>
        {careerData.milestones.map((milestone, i) => {
          const isCurrent = i === estimatedLevel;
          const isPast = i < estimatedLevel;
          const isOpen = selectedLevel === milestone.id;
          return (
            <motion.div key={milestone.id} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }} className={`glass-card overflow-hidden ${isCurrent ? "border-yellow-500/30" : ""}`}>
              <button onClick={() => setSelectedLevel(isOpen ? null : milestone.id)} className="w-full flex items-center gap-4 p-4 text-left hover:bg-white/5 transition-colors">
                <div className="relative">
                  <span className="text-2xl">{milestone.icon}</span>
                  {isPast && <Check className="w-3 h-3 text-cyber-green absolute -top-1 -right-1" />}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-bold" style={{ color: milestone.color }}>{milestone.level}</h3>
                    {isCurrent && <span className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-yellow-500/20 text-yellow-400 border border-yellow-500/30 animate-pulse">YOU ARE HERE</span>}
                    {isPast && <span className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-cyber-green/20 text-cyber-green border border-cyber-green/30">✓ ACHIEVED</span>}
                  </div>
                  <p className="text-xs text-gray-500 mt-0.5">{milestone.range}</p>
                </div>
                {/* Level progress indicator */}
                <div className="flex gap-0.5 shrink-0">
                  {[...Array(8)].map((_, j) => (
                    <div key={j} className={`w-1.5 h-4 rounded-full ${j <= i && j <= estimatedLevel ? "bg-cyber-green" : j <= i ? "bg-dark-600" : "bg-dark-700"}`} />
                  ))}
                </div>
                <ChevronRight className={`w-5 h-5 text-gray-600 transition-transform ${isOpen ? "rotate-90" : ""}`} />
              </button>
              {isOpen && (
                <motion.div initial={{ height: 0 }} animate={{ height: "auto" }} className="border-t border-dark-600/50 p-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-xs font-mono text-gray-500 mb-2 uppercase flex items-center gap-1"><Briefcase className="w-3 h-3" />Required Skills</h4>
                      <div className="space-y-1">{milestone.skills.map((s) => <div key={s} className="text-xs text-gray-400 flex items-center gap-2"><Star className="w-3 h-3 shrink-0" style={{ color: milestone.color }} />{s}</div>)}</div>
                    </div>
                    <div>
                      <h4 className="text-xs font-mono text-gray-500 mb-2 uppercase flex items-center gap-1"><Target className="w-3 h-3" />Milestone Tasks</h4>
                      <div className="space-y-1">{milestone.tasks.map((t) => <div key={t} className="text-xs text-gray-400 flex items-center gap-2"><Target className="w-3 h-3 text-gray-600 shrink-0" />{t}</div>)}</div>
                    </div>
                  </div>
                  {/* Time estimate */}
                  <div className="mt-4 p-3 bg-dark-800/50 rounded-lg border border-dark-600/30 flex items-center gap-3">
                    <Clock className="w-4 h-4 text-gray-500" />
                    <p className="text-xs text-gray-400">Estimated time to reach: <span className="text-white font-mono">{Math.max(1, (i - estimatedLevel) * 3)} - {Math.max(3, (i - estimatedLevel) * 6)} months</span> with consistent practice</p>
                  </div>
                </motion.div>
              )}
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
